server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-evento
              uri: lb://evento
              predicates:
                - Path=/api/v1/eventos/**
            - id: ms-inscricao
              uri: lb://inscricao
              predicates:
                - Path=/api/v1/inscricoes/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka